Update `composer` to v2.3.9
laminas/laminas-continuous-integration-action pull request #101
Opened 2022-07-05 16:57 UTC by boesing

|    Q          |   A
|-------------- | ------
| Bugfix        | yes
| QA            | yes

### Description

With one of the latest releases, `composer` was updated to a version which treated the absence of `allow-plugins` within `composer.extra` as "do not install any composer-plugin".
This seems to be fixed in the latest 2.3.9 release.

We can test the latest release with https://github.com/laminas/laminas-cache-storage-adapter-apcu/runs/7174123645?check_suite_focus=true as it already fails there.

2022-07-05 16:58 UTC, Ocramius requested changes
```
Error: buildx failed with: error: failed to solve: composer:2.3.9: docker.io/library/composer:2.3.9: not found
```

Too soon?

2022-07-05 17:00 UTC, boesing commented
Maybe. But even 2.3.8 which was released 4 days ago is not available...

2022-07-05 17:24 UTC, boesing commented
I created an issue in https://github.com/composer/composer/issues/10926
I suggested an additional push to the github docker image hosting - not sure if composer wants this extra redundancy but the idea behind my suggestion was that it can be automated. 
Having manual steps to actually release stuff seems to be a problem, especially when it comes to more frequent releases.

2022-07-10 18:54 UTC, Ocramius approved these changes

2022-07-10 18:54 UTC, merged

2022-07-10 18:55 UTC, Ocramius commented
Thanks @boesing!